"""Signal dataclass for strategy evaluation outputs."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Optional


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy.

    Attributes:
        direction: Signal direction from -1.0 (strong sell) to +1.0 (strong buy).
            0.0 means neutral/no signal.
        confidence: Confidence level from 0.0 to 1.0.
        reasoning: Human-readable explanation of why the signal was generated.
        strategy_id: ID of the strategy that generated this signal.
        symbol: The asset symbol the signal applies to.
        timestamp: When the signal was generated.
        metadata: Additional strategy-specific data (e.g., indicator values).
    """

    direction: float = 0.0
    confidence: float = 0.0
    reasoning: str = ""
    strategy_id: str = ""
    symbol: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal values after initialization."""
        if not -1.0 <= self.direction <= 1.0:
            raise ValueError(
                f"Direction must be between -1.0 and 1.0, got {self.direction}"
            )
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Confidence must be between 0.0 and 1.0, got {self.confidence}"
            )

    @property
    def is_buy(self) -> bool:
        """Check if this is a buy signal (direction > 0)."""
        return self.direction > 0.0

    @property
    def is_sell(self) -> bool:
        """Check if this is a sell signal (direction < 0)."""
        return self.direction < 0.0

    @property
    def is_neutral(self) -> bool:
        """Check if this is a neutral signal (direction == 0)."""
        return self.direction == 0.0

    @property
    def strength(self) -> float:
        """Absolute signal strength (0.0 to 1.0)."""
        return abs(self.direction)

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for serialization."""
        return {
            "direction": self.direction,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }
